//! The **RPC contract** (ADR-0029): each Jedi RPC method with its RPC surface,
//! its params type and its result type. One `entry!` line per method. The macro
//! takes the method name from the handler identifier, as `router_builder!`
//! does, and reads the params and result types from the handler through
//! rpc-router's `Handler` bound. So this module declares no type of its own.
//!
//! `export_bindings_rpc_contract` writes `bindings/RpcContract.ts`, and the
//! routing test proves that each method is routed on its own surface.
//!
//! The FullStack methods stay outside the contract until #128 removes them.
//! The module is `#[cfg(test)]`: only the tests read it, and the web-server
//! bin crate fails `cgs check` on unused items.

use super::{
	all_rpc_router_builder, caption_rpc, category_rpc, hero_rpc, post_rpc,
	profile_rpc, public_rpc_router_builder,
};
use lib_rpc_core::{ts_dependencies, RpcData, RpcParamsTs};
use rpc_router::{CallError, CallResult, Handler, Router};
use std::collections::BTreeMap;
use std::fs;
use ts_rs::{Config, Dependency, TS};

type Result<T> = core::result::Result<T, Box<dyn std::error::Error>>;

// region:    --- Contract

/// The RPC surface that a method is registered on.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Surface {
	/// `/api/rpc`, login required (`all_rpc_router_builder`).
	Authenticated,
	/// `/api/rpc-public`, no login (`public_rpc_router_builder`).
	Public,
}

/// One method of the contract. The type fields hold the TypeScript form of
/// the handler's params and result types.
struct Entry {
	surface: Surface,
	method: &'static str,
	params: fn(&Config) -> String,
	result: fn(&Config) -> String,
	dependencies: fn(&Config) -> Vec<Dependency>,
}

/// Build an `Entry` from a handler. `P` and `R` are the handler's params and
/// result types, as rpc-router's `Handler` bound reads them.
fn new_entry<F, T, P, R>(
	surface: Surface,
	method: &'static str,
	_handler: F,
) -> Entry
where
	F: Handler<T, P, R>,
	T: Send + Sync + 'static,
	P: RpcParamsTs + Send + Sync + 'static,
	R: RpcData + Send + Sync + 'static,
{
	Entry {
		surface,
		method,
		params: P::ts_name,
		result: <R::Data as TS>::name,
		dependencies: entry_dependencies::<P, R>,
	}
}

fn entry_dependencies<P: RpcParamsTs, R: RpcData>(cfg: &Config) -> Vec<Dependency> {
	let mut deps = P::ts_dependencies(cfg);
	deps.extend(ts_dependencies::<R::Data>(cfg));
	deps
}

/// `entry!(Surface, module::handler)`: the method name is the handler name.
macro_rules! entry {
	($surface:ident, $module:ident :: $handler:ident) => {
		new_entry(Surface::$surface, stringify!($handler), $module::$handler)
	};
}

/// The 14 Jedi methods. A new Jedi RPC adds one line here; until then, no
/// typed front-end call can reach it.
fn contract() -> Vec<Entry> {
	vec![
		// -- Authenticated
		entry!(Authenticated, caption_rpc::add_caption),
		entry!(Authenticated, caption_rpc::get_caption_like),
		entry!(Authenticated, caption_rpc::toggle_caption_like),
		entry!(Authenticated, hero_rpc::update_hero),
		entry!(Authenticated, post_rpc::create_post),
		entry!(Authenticated, post_rpc::get_post_like),
		entry!(Authenticated, post_rpc::toggle_post_like),
		entry!(Authenticated, profile_rpc::get_profile),
		// -- Public
		entry!(Public, caption_rpc::list_captions_for_post),
		entry!(Public, category_rpc::list_categories),
		entry!(Public, hero_rpc::get_hero),
		entry!(Public, post_rpc::featured_post),
		entry!(Public, post_rpc::get_post),
		entry!(Public, post_rpc::list_posts),
	]
}

// endregion: --- Contract

// region:    --- Export

/// Render `RpcContract.ts`: the imports, then one type per surface that maps
/// each method to its `params` and `result`.
fn render(cfg: &Config, contract: &[Entry]) -> String {
	// One import per binding, sorted by name.
	let imports: BTreeMap<String, String> = contract
		.iter()
		.flat_map(|e| (e.dependencies)(cfg))
		.map(|dep| {
			let path = dep.output_path.to_string_lossy();
			let path = path.strip_suffix(".ts").unwrap_or(&path).to_string();
			(dep.ts_name, path)
		})
		.collect();

	let mut out = String::from(
		"// This file was generated by `export_bindings_rpc_contract` (web-server \
		 `web/rpcs/rpc_contract.rs`, ADR-0029). Do not edit this file manually.\n",
	);
	for (name, path) in &imports {
		out.push_str(&format!("import type {{ {name} }} from \"./{path}\";\n"));
	}

	let surfaces = [
		(
			Surface::Authenticated,
			"AuthenticatedRpc",
			"The authenticated RPC surface (`/api/rpc`, login required).",
		),
		(
			Surface::Public,
			"PublicRpc",
			"The public RPC surface (`/api/rpc-public`, no login).",
		),
	];
	for (surface, type_name, doc) in surfaces {
		out.push_str(&format!("\n/** {doc} */\nexport type {type_name} = {{\n"));
		for e in contract.iter().filter(|e| e.surface == surface) {
			out.push_str(&format!(
				"  {}: {{ params: {}; result: {} }};\n",
				e.method,
				(e.params)(cfg),
				(e.result)(cfg),
			));
		}
		out.push_str("};\n");
	}
	out
}

// endregion: --- Export

// region:    --- Tests

/// Write `bindings/RpcContract.ts`. `cgs bindings` runs it, and the CI
/// bindings-drift guard checks the file.
#[test]
fn export_bindings_rpc_contract() -> Result<()> {
	let cfg = Config::from_env();
	fs::write(
		cfg.out_dir().join("RpcContract.ts"),
		render(&cfg, &contract()),
	)?;
	Ok(())
}

/// Each contract entry is routed on its own surface, and only there; the public
/// router lists exactly the public entries. Each call carries no params and the
/// routers carry no resources, so no handler body runs: the test needs no
/// database and no login.
#[tokio::test]
async fn rpc_contract_routes_each_method_on_its_surface() -> Result<()> {
	let authenticated = all_rpc_router_builder().build();
	let public = public_rpc_router_builder().build();

	for e in contract() {
		let (own, other) = match e.surface {
			Surface::Authenticated => (&authenticated, &public),
			Surface::Public => (&public, &authenticated),
		};
		// Routed on its own surface.
		assert!(
			!is_method_unknown(own.call_route(None, e.method, None).await),
			"`{}` is not routed on its {:?} surface",
			e.method,
			e.surface
		);
		// Not routed on the other surface.
		assert!(
			is_method_unknown(other.call_route(None, e.method, None).await),
			"`{}` is also routed on the surface other than {:?}",
			e.method,
			e.surface
		);
	}

	// The public router lists exactly the public entries. The public surface
	// runs under `root_ctx`, so it must carry no method that the contract does
	// not list as public.
	let mut public_entries: Vec<String> = contract()
		.into_iter()
		.filter(|e| e.surface == Surface::Public)
		.map(|e| e.method.to_string())
		.collect();
	public_entries.sort();
	let public_routes = route_names(&public)?;
	assert_eq!(public_routes, public_entries);

	Ok(())
}

fn is_method_unknown(res: CallResult) -> bool {
	matches!(
		res,
		Err(CallError {
			error: rpc_router::Error::MethodUnknown,
			..
		})
	)
}

/// The method names of a router, read from its `Debug` output. rpc-router
/// keeps its method map private (ADR-0016), but its `Debug` output lists the
/// names as `route_by_name: ["a", "b"]`. A format change fails this read.
fn route_names(router: &Router) -> Result<Vec<String>> {
	const KEY: &str = "route_by_name: [";
	let debug = format!("{router:?}");
	let start = debug
		.find(KEY)
		.ok_or("no `route_by_name` in the router Debug")?
		+ KEY.len();
	let len = debug[start..]
		.find(']')
		.ok_or("no `]` after `route_by_name`")?;
	let mut names: Vec<String> = debug[start..start + len]
		.split(", ")
		.map(|name| name.trim_matches('"').to_string())
		.collect();
	names.sort();
	Ok(names)
}

// endregion: --- Tests
