// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Agent = { id: number, owner_id: number, name: string, ai_provider: string, ai_model: string, cid: number, ctime: string, mid: number, mtime: string, };
