// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The **author snapshot** a content entity carries: the owning User's public
 * identity — `id`, display `name` (the `username`), and `avatar_url`. It is the
 * author half of a `PostView` (and, later, `CaptionView` / `CommentView`), so a
 * consumer renders authorship without a second read.
 *
 * A public projection (ADR-0021): it carries no audit columns. `name` is the
 * User's `username`; the query aliases it so a rename of the wire field does not
 * touch the column.
 */
export type AuthorRef = { id: bigint, name: string, avatar_url: string | null, };
