// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `add_caption` input (#121). The Owner is the caller (`ctx`), never the
 * payload. Exported so the front-end sends the one wire shape.
 */
export type CaptionForCreate = { post_id: number, text: string, };
