// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorRef } from "./AuthorRef.d";

/**
 * The enriched **public projection** of a Caption (ADR-0021): the author
 * snapshot and the derived like / comment counts, assembled at the model seam
 * so the front-end renders without joining. It carries no audit columns
 * (`cid` / `mid` / `ctime` / `mtime`).
 */
export type CaptionView = { id: bigint, post_id: bigint, author: AuthorRef, text: string, like_count: bigint, comment_count: bigint, };
