// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The public projection of a Category: only the fields an anonymous consumer
 * needs. The audit columns (`cid` / `mid` actor ids, `ctime` / `mtime`) are
 * deliberately absent, so the public `/api/rpc-public` response never exposes
 * internal storage detail (#116 review). `base::list` selects exactly these
 * columns for this type, so the audit columns are never even queried.
 */
export type CategoryPublic = { id: bigint, name: string, icon: string, };
