// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A static, back-end-owned taxonomy row. It has no `owner_id` and no AI fields
 * (ADR-0011). `icon` is an opaque key the back-end never interprets; the
 * front-end maps it to a sprite name with a fallback.
 */
export type Category = { id: bigint, name: string, icon: string, cid: bigint, ctime: string, mid: bigint, mtime: string, };
