// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConvMsg = { id: number, conv_id: number, user_id: number, content: string, cid: number, ctime: string, mid: number, mtime: string, };
