// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConvKind } from "./ConvKind.d";
import type { ConvState } from "./ConvState.d";

export type Conv = { id: number, agent_id: number, owner_id: number, title: string | null, kind: ConvKind, state: ConvState, cid: number, ctime: string, mid: number, mtime: string, };
