// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `update_hero` input. Each field is optional: a missing or `null` field
 * is left unchanged.
 */
export type HeroForUpdate = { title?: string | null, subtitle?: string | null, cta_text?: string | null, background_image?: string | null, };
