// This file was generated by `export_bindings_hygiene_caps` (lib-core `model/base/hygiene.rs`, ADR-0029). Do not edit this file manually.

/** Each write-path length cap (`DbBmc::hygiene_rules`, ADR-0019), keyed by table and field. */
export type HygieneCaps = {
  post: {
    title: 36;
    image_alt: 200;
    photographer: 120;
    image_src: 1024;
    photographer_url: 1024;
    source_url: 1024;
  };
  caption: {
    text: 36;
  };
  hero: {
    title: 40;
    subtitle: 100;
    cta_text: 20;
    background_image: 1024;
  };
  category: {
    name: 20;
  };
};
