// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibAuthError } from "./lib_auth_Error.d";
import type { LibAuthTokenError } from "./lib_auth_token_Error.d";
import type { LibCoreError } from "./lib_core_Error.d";
import type { LibRpcCoreError } from "./lib_rpc_core_Error.d";
import type { CtxExtError } from "./lib_web_middleware_Error.d";

export type LibWebError = { "type": "LoginFailUsernameNotFound" } | { "type": "LoginFailUserHasNoPwd", "data": { user_id: bigint, } } | { "type": "LoginFailPwdNotMatching", "data": { user_id: bigint, } } | { "type": "CtxExt", "data": CtxExtError } | { "type": "ReqStampNotInReqExt" } | { "type": "Model", "data": LibCoreError } | { "type": "Pwd", "data": LibAuthError } | { "type": "Token", "data": LibAuthTokenError } | { "type": "Rpc", "data": LibRpcCoreError } | { "type": "RpcLibRpc", "data": LibRpcCoreError } | { "type": "RpcHandlerErrorUnhandled", "data": string } | { "type": "RpcRouter", "data": { method: string, } } | { "type": "SerdeJson", "data": string };
