// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibAuthError } from "./lib_auth_Error.d";
import type { LibCoreDbxError } from "./lib_core_dbx_Error.d";

export type LibCoreError = { "EntityNotFound": { entity: string, id: bigint, } } | { "ListLimitOverMax": { max: bigint, actual: bigint, } } | "CountFail" | { "UserAlreadyExists": { username: string, } } | { "UniqueViolation": { table: string, constraint: string, } } | { "CantCreateModelManagerProvider": string } | { "Pwd": LibAuthError } | { "Dbx": LibCoreDbxError } | { "SeaQuery": string } | { "ModqlIntoSea": string };
