// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibAuthPwdError } from "./lib_auth_pwd_Error.d";

export type LibAuthError = "PwdWithSchemeFailedParse" | "FailSpawnBlockForValidate" | "FailSpawnBlockForHash" | { "Scheme": LibAuthPwdError };
