// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `toggle_*_like` input (#122, #123). `id` is the parent id. `liked` is the
 * wanted state, not a flip, so the toggle is idempotent: a second like and a
 * second unlike are no-ops.
 */
export type LikeForToggle = { id: number, liked: boolean, };
