// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One User's view of one Like target's Likes (#122, #123): the derived like
 * count and whether the caller likes it. `id` is the parent id (the Post or the
 * Caption). Per-caller, so it is served only on the authenticated surface — an
 * anonymous public projection cannot carry `liked`.
 */
export type LikeView = { id: number, like_count: number, liked: boolean, };
