// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params structure for any RPC Create call.
 */
export type ParamsForCreate<D> = { data: D, };
