// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params structure for an RPC List call scoped to one parent entity (e.g. a
 * Post's Captions): `id` names the parent, and the optional `list_options`
 * pages the result. The export holds only `id`: `list_options` stays on the
 * back-end until a front-end caller needs it (#176).
 */
export type ParamsIdedList = { id: number, };
