// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorRef } from "./AuthorRef.d";
import type { CategoryPublic } from "./CategoryPublic.d";

/**
 * The enriched **public projection** of a Post (ADR-0021): the author snapshot,
 * the resolved Categories, and the derived like / comment counts, assembled at
 * the model seam so the front-end renders without joining. It carries no audit
 * columns (`cid` / `mid` / `ctime` / `mtime`).
 */
export type PostView = { id: bigint, author: AuthorRef, title: string, image_src: string, image_alt: string, photographer: string, photographer_url: string, source_url: string, categories: Array<CategoryPublic>, like_count: bigint, comment_count: bigint, };
