// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `toggle_post_like` input (#122). `liked` is the wanted state, not a flip,
 * so the toggle is idempotent: a second like and a second unlike are no-ops.
 */
export type PostLikeForToggle = { post_id: number, liked: boolean, };
