// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One User's view of one Post's Likes (#122): the derived like count and
 * whether the caller likes the Post. Per-caller, so it is served only on the
 * authenticated surface — the anonymous `PostView` cannot carry `liked`.
 */
export type PostLikeView = { post_id: bigint, like_count: bigint, liked: boolean, };
