// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `create_post` input (#120). `category_ids` is not a `post` column — the
 * `#[field(skip)]` keeps it out of the insert — so `PostBmc::create` writes it as
 * the `post_category` links. Exported so the front-end sends the one wire shape.
 */
export type PostForCreate = { title: string, image_src: string, image_alt: string, photographer: string, photographer_url: string, source_url: string, category_ids: Array<bigint>, };
