// This file was generated by `export_bindings_rpc_contract` (web-server `web/rpcs/rpc_contract.rs`, ADR-0029). Do not edit this file manually.
import type { AuthorRef } from "./AuthorRef.d";
import type { CaptionForCreate } from "./CaptionForCreate.d";
import type { CaptionView } from "./CaptionView.d";
import type { CategoryPublic } from "./CategoryPublic.d";
import type { HeroForUpdate } from "./HeroForUpdate.d";
import type { HeroView } from "./HeroView.d";
import type { LikeForToggle } from "./LikeForToggle.d";
import type { LikeView } from "./LikeView.d";
import type { ParamsForCreate } from "./ParamsForCreate.d";
import type { ParamsForUpdate } from "./ParamsForUpdate.d";
import type { ParamsIded } from "./ParamsIded.d";
import type { ParamsIdedList } from "./ParamsIdedList.d";
import type { PostForCreate } from "./PostForCreate.d";
import type { PostView } from "./PostView.d";

/** The authenticated RPC surface (`/api/rpc`, login required). */
export type AuthenticatedRpc = {
  add_caption: { params: ParamsForCreate<CaptionForCreate>; result: CaptionView };
  get_caption_like: { params: ParamsIded; result: LikeView };
  toggle_caption_like: { params: ParamsForCreate<LikeForToggle>; result: LikeView };
  update_hero: { params: ParamsForUpdate<HeroForUpdate>; result: HeroView };
  create_post: { params: ParamsForCreate<PostForCreate>; result: PostView };
  get_post_like: { params: ParamsIded; result: LikeView };
  toggle_post_like: { params: ParamsForCreate<LikeForToggle>; result: LikeView };
  get_profile: { params: undefined; result: AuthorRef };
};

/** The public RPC surface (`/api/rpc-public`, no login). */
export type PublicRpc = {
  list_captions_for_post: { params: ParamsIdedList; result: Array<CaptionView> };
  list_categories: { params: undefined; result: Array<CategoryPublic> };
  get_hero: { params: undefined; result: HeroView };
  featured_post: { params: undefined; result: PostView };
  get_post: { params: ParamsIded; result: PostView };
  list_posts: { params: undefined; result: Array<PostView> };
};
