// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTyp } from "./UserTyp.d";

export type User = { id: number, username: string, typ: UserTyp, avatar_url: string | null, };
