// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConvMsg } from "./ConvMsg.d";

/**
 * The realtime feed envelope, a discriminated union tagged by `event_type`
 * (internal serde tagging). ts-rs exports it, so the front-end narrows on the
 * tag and reads a typed payload — no cast. `conv_msg` carries the new `ConvMsg`;
 * the two list-feed pokes are payload-less (#85). The routing `channel` is
 * derived from the variant (see the `channel` method below), not carried on the
 * wire.
 */
export type WsEvent = { "event_type": "conv_msg", payload: ConvMsg, } | { "event_type": "agent_update" } | { "event_type": "conv_update" };
