// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel.d";
import type { ConvMsg } from "./ConvMsg.d";

/**
 * The realtime feed envelope, a discriminated union tagged by `event_type`
 * (internal serde tagging). ts-rs exports it, so the front-end narrows on the
 * tag and reads a typed payload — no cast. `conv_msg` carries the new `ConvMsg`.
 * Every contentless poke is one `Poke` variant carrying its [`Channel`] (#85):
 * the poke pushes no domain row, only the id its routing key needs, held inside
 * the `Channel`. A subscriber refetches through the scoped `list_*` RPC. The two
 * Jedi comment channels (`post_comment`, `caption_comment`) push a payload
 * (`CommentView`); that payload is not built yet (#113), so they gain no payload
 * variant here — they are subscribe-only (#115). The routing `Channel` is derived
 * from the event (see the `channel` method below), not carried as a separate
 * field: a payload event reads it from the payload, a poke carries it (ADR-0020).
 */
export type WsEvent = { "event_type": "conv_msg", payload: ConvMsg, } | { "event_type": "poke" } & Channel;
