---- Base app schema

-- Org
CREATE TABLE "org" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name varchar(128) NOT NULL UNIQUE,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,
  typ user_typ NOT NULL DEFAULT 'User',

  -- Profile
  --   Persisted avatar URL (#117). The merge moves the avatar off the front-end
  --   useAuth seam onto the User row, so the author snapshot on a Post, Caption,
  --   or Comment reads one back-end identity (ADR-0007, ADR-0011 addendum).
  avatar_url varchar(1024),

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Agent

CREATE TABLE agent (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  owner_id BIGINT NOT NULL,

  -- Properties
  name varchar(256) NOT NULL,
  ai_provider varchar(256) NOT NULL default 'dev', -- For now only support 'dev' provider
  ai_model varchar(256) NOT NULL default 'parrot', -- For now only support 'parrot' model

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Category
--   A static, back-end-owned taxonomy: no owner_id, no AI fields. The icon is
--   an opaque key the back-end never interprets (ADR-0011). The front-end maps
--   it to a sprite name with a fallback.
CREATE TABLE category (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties
  name varchar(256) NOT NULL,
  icon varchar(256) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

-- Conv
CREATE TYPE conv_kind AS ENUM ('OwnerOnly', 'MultiUsers');

CREATE TYPE conv_state AS ENUM ('Active', 'Archived');

CREATE TABLE conv (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  owner_id BIGINT NOT NULL,
  agent_id BIGINT NOT NULL,

  -- Properties
  title varchar(256),
  kind conv_kind NOT NULL default 'OwnerOnly',
  state conv_state NOT NULL default 'Active',

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE conv ADD CONSTRAINT fk_conv_agent
  FOREIGN KEY (agent_id) REFERENCES "agent"(id)
  ON DELETE CASCADE;


-- Conv Participants
CREATE TABLE conv_user (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties / FKs
  conv_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL, 

  -- Machine User Properties
  auto_respond BOOLEAN NOT NULL DEFAULT false,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL    
);

-- Conv Messages
CREATE TABLE conv_msg (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  conv_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL, -- should be came as cid

  -- Properties
  content varchar(1024) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

ALTER TABLE conv_msg ADD CONSTRAINT fk_conv_msg_conv
  FOREIGN KEY (conv_id) REFERENCES "conv"(id)
  ON DELETE CASCADE;

-- conv_user participants cascade from BOTH parents: the Conversation joined and
-- the User who joins. The conv link was absent, so a deleted Conversation (e.g.
-- cascaded from a deleted agent via fk_conv_agent) would orphan its participant
-- rows once ConvUserBmc is implemented (see conv_user.rs). fk_conv_user_conv now
-- guards conv_id, and the user link is renamed fk_conv_user_user.
ALTER TABLE conv_user ADD CONSTRAINT fk_conv_user_conv
  FOREIGN KEY (conv_id) REFERENCES "conv"(id)
  ON DELETE CASCADE;

ALTER TABLE conv_user ADD CONSTRAINT fk_conv_user_user
  FOREIGN KEY (user_id) REFERENCES "user"(id)
  ON DELETE CASCADE;

---- Jedi merged schema (#117)

-- Post
--   The core feed entity: a shared Flickr photo. Every Post is public — read is
--   unscoped, write is owner-only (ADR-0011, #106). It carries an owner, an
--   external photographer attribution, and, via post_category, at least one
--   Category. Derived like / comment counts come from post_like / post_comment.
CREATE TABLE post (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  owner_id BIGINT NOT NULL,

  -- Properties
  title varchar(256) NOT NULL,
  image_src varchar(1024) NOT NULL,
  image_alt varchar(256) NOT NULL,
  photographer varchar(256) NOT NULL,
  photographer_url varchar(1024) NOT NULL,
  source_url varchar(1024) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

ALTER TABLE post ADD CONSTRAINT fk_post_owner
  FOREIGN KEY (owner_id) REFERENCES "user"(id)
  ON DELETE CASCADE;

-- Post <-> Category join
--   Many-to-many, minimum one Category per Post (#107). Category resolution reads
--   this join with a portable batched IN query, never array_agg (#117).
CREATE TABLE post_category (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  post_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

ALTER TABLE post_category ADD CONSTRAINT fk_post_category_post
  FOREIGN KEY (post_id) REFERENCES "post"(id)
  ON DELETE CASCADE;

-- RESTRICT, not CASCADE: a Category in use may not be deleted, because a Post
-- must keep at least one Category (#107). Cascading here would silently orphan a
-- Post whose only Category is removed. The post side (below) still cascades.
ALTER TABLE post_category ADD CONSTRAINT fk_post_category_category
  FOREIGN KEY (category_id) REFERENCES "category"(id)
  ON DELETE RESTRICT;

-- Post Likes
--   One User's endorsement of one Post (#106). Empty at seed, so a Post's derived
--   like count resolves to 0 until likes land (#118). The like count is derived by
--   COUNT over this table, never stored on the Post.
CREATE TABLE post_like (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,

  -- At most one Like per (Post, User): a User's endorsement counts once even if
  -- they click twice (#106, #122). The one-like invariant lives at the DB, not in
  -- application code, so a double-insert race cannot create a second Like.
  CONSTRAINT uq_post_like_post_user UNIQUE (post_id, user_id),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

ALTER TABLE post_like ADD CONSTRAINT fk_post_like_post
  FOREIGN KEY (post_id) REFERENCES "post"(id)
  ON DELETE CASCADE;

ALTER TABLE post_like ADD CONSTRAINT fk_post_like_user
  FOREIGN KEY (user_id) REFERENCES "user"(id)
  ON DELETE CASCADE;

-- Post Comments
--   A User's remark in a Post's thread (#108). Empty at seed, so a Post's derived
--   comment count resolves to 0 until Comments land. The comment count is derived
--   by COUNT over this table, never stored on the Post.
CREATE TABLE post_comment (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FKs
  post_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,

  -- Properties
  content varchar(1024) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

ALTER TABLE post_comment ADD CONSTRAINT fk_post_comment_post
  FOREIGN KEY (post_id) REFERENCES "post"(id)
  ON DELETE CASCADE;

ALTER TABLE post_comment ADD CONSTRAINT fk_post_comment_owner
  FOREIGN KEY (owner_id) REFERENCES "user"(id)
  ON DELETE CASCADE;
